### ISSUE TITLE
Some channels not working.

### ISSUE THREAD

**Issue by moolyadee** [freeview/iptv#28]
Only Astro Awani works. RTM1 and RTM2 does not work.

**Comment by moolyadee** [comment]
Mind adding TV3 too?

**Comment by ah-svc** [comment]
Hi, I have just checked all of my streams are working fine. There are a few
factors that may cause your problem:

   - RTM streams are geo-locked. You will need to have Malaysian IP address
   to view them.
   - RTM and MediaPrima (TV3 etc.) will need additional headers such as
   Referer, only some IPTV/Video players support this, such as Tivimate or
   Tvirl. I believe most IPTV add-ons in Kodi support this.
   - MediaPrima streams are updated 6 times a day. You will need to update
   the playlist URL or have an IPTV player that auto-update, otherwise your
   streams will die.

Let me know if you have any additional questions.

Best regards,
Akmal

**Comment by Arsyad1105** [comment]
RTM Channel can support some ip only. Not working with malaysia vpn too.

**Comment by akmalharith** [comment]
> RTM Channel can support some ip only. Not working with malaysia vpn too.

What player are you using? They work fine as long as you are on Malaysian network. Make sure your player support the `Referer` header.

**Comment by Arsyad1105** [comment]
> > RTM Channel can support some ip only. Not working with malaysia vpn too.
> 
> What player are you using? They work fine as long as you are on Malaysian network. Make sure your player support the `Referer` header.

For now Kodi is working properly. I have try lot of m3u player but just Kodi can. Can you tell me what player can use for rtm channel because Kodi take lot of storage on my phone.

**Comment by akmalharith** [comment]
The playlist is for Android TV. Most Android TV players can support like Tivimate or TVirl. They are not supported on Android phone. Check out the Readme page https://github.com/freeview/iptv/blob/master/README.MD.

**Comment by Badlish** [comment]
Salam Akmal.

I can retrieve using url github playlist but no TV3, TV9, Hijrah and most Astro channels.. 

Thank you bro
